export const API_BASE_PATHS = {
	AUTH: '/auth',
	ROOM: '/room',
} as const;

export const ROOM_ROUTES = {
	CREATE: '/create',
	JOIN: '/join',
	LIST_ACTIVE: '/active',
	ONBOARD: '/onboard',
	USERS: '/users',
	GET_MISSING_PACKET: '',
} as const;

export const AUTH_ROUTES = {
	LOGIN: '/login',
	REGISTER: '/register',
	REFRESH: '/refresh',
	LOGOUT: '/logout',
	UPDATE: '/update',
} as const;

export const ROOM_API = {
	CREATE: `${API_BASE_PATHS.ROOM}${ROOM_ROUTES.CREATE}`,
	JOIN: `${API_BASE_PATHS.ROOM}${ROOM_ROUTES.JOIN}`,
	LIST_ACTIVE: `${API_BASE_PATHS.ROOM}${ROOM_ROUTES.LIST_ACTIVE}`,
	ONBOARD: `${API_BASE_PATHS.ROOM}${ROOM_ROUTES.ONBOARD}`,
	USERS: `${API_BASE_PATHS.ROOM}${ROOM_ROUTES.USERS}`,
	GET_MISSING_PACKET: `${API_BASE_PATHS.ROOM}`,
} as const;

export const AUTH_API = {
	REGISTER: `${API_BASE_PATHS.AUTH}${AUTH_ROUTES.REGISTER}`,
	LOGIN: `${API_BASE_PATHS.AUTH}${AUTH_ROUTES.LOGIN}`,
	UPDATE: `${API_BASE_PATHS.AUTH}${AUTH_ROUTES.UPDATE}`,
	LOGOUT: `${API_BASE_PATHS.AUTH}${AUTH_ROUTES.LOGOUT}`,
	REFRESH: `${API_BASE_PATHS.AUTH}${AUTH_ROUTES.REFRESH}`,
};
